name: base
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - altair=5.1.2
  - ipykernel=6.26.0
  - libtiff=4.6.0
  - matplotlib=3.8.1
  - nb_conda_kernels=2.3.1
  - pip=23.3.1
  - python=3.11.6
  - pytest=7.4.3
  - scikit-learn=1.3.2
  - scipy=1.11.3
  - vl-convert-python=1.1.0
  - vegafusion=1.4.3
  - vegafusion-python-embed=1.4.3
  - vegafusion-jupyter=1.4.3
  - vega_datasets=0.9.0
  - folium=0.15.0
  - seaborn=0.13.0
